/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lottogui;

import javax.swing.JOptionPane;

/**
 *
 * @author x15015556
 */
public class LottoPhase2GUI extends javax.swing.JFrame {
    
    private int[] secretMain;
    private int[] secretPlus1;
    private int[] secretPlus2;
    private final int[][] num = new int[3][5];
    private int correctL1Main; //correctL1 (correct Line 1 -- checking if a number matches secret/result
    private int correctL2Main;
    private int correctL3Main;
    private int correctL1Plus1; //correctL1 (correct Line 1 -- checking if a number matches secret/result
    private int correctL2Plus1;
    private int correctL3Plus1;
    private int correctL1Plus2; //correctL1 (correct Line 1 -- checking if a number matches secret/result
    private int correctL2Plus2;
    private int correctL3Plus2;
    private String playingLottoPlus;
    /**
     * Creates new form LottoPhase2GUI
     */
    public LottoPhase2GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        headingLbl = new javax.swing.JLabel();
        yesBtn = new javax.swing.JButton();
        noBtn = new javax.swing.JButton();
        playingPlusLbl = new javax.swing.JLabel();
        selectLbl = new javax.swing.JLabel();
        line1Lbl = new javax.swing.JLabel();
        line00Tf = new javax.swing.JTextField();
        line01Tf = new javax.swing.JTextField();
        line02Tf = new javax.swing.JTextField();
        line03Tf = new javax.swing.JTextField();
        line10Tf = new javax.swing.JTextField();
        line11Tf = new javax.swing.JTextField();
        line12Tf = new javax.swing.JTextField();
        line13Tf = new javax.swing.JTextField();
        line04Tf = new javax.swing.JTextField();
        line14Tf = new javax.swing.JTextField();
        line20Tf = new javax.swing.JTextField();
        line21Tf = new javax.swing.JTextField();
        line22Tf = new javax.swing.JTextField();
        line23Tf = new javax.swing.JTextField();
        line24Tf = new javax.swing.JTextField();
        playGameBtn = new javax.swing.JButton();
        line2Lbl = new javax.swing.JLabel();
        line3Lbl = new javax.swing.JLabel();
        plus1Results2Lbl1 = new javax.swing.JLabel();
        displayResults4Lbl = new javax.swing.JLabel();
        displayResults3Lbl = new javax.swing.JLabel();
        displayResults2Lbl = new javax.swing.JLabel();
        displayResults1Lbl = new javax.swing.JLabel();
        displayResults0Lbl = new javax.swing.JLabel();
        resultsLbl = new javax.swing.JLabel();
        resultsLbl1 = new javax.swing.JLabel();
        displayPlus1_0Lbl = new javax.swing.JLabel();
        displayPlus1_1Lbl = new javax.swing.JLabel();
        displayPlus1_2Lbl = new javax.swing.JLabel();
        displayPlus1_3Lbl = new javax.swing.JLabel();
        displayPlus1_4Lbl = new javax.swing.JLabel();
        resultsLbl2 = new javax.swing.JLabel();
        displayPlus2_0Lbl = new javax.swing.JLabel();
        displayPlus2_1Lbl = new javax.swing.JLabel();
        displayPlus2_2Lbl = new javax.swing.JLabel();
        displayPlus2_3Lbl = new javax.swing.JLabel();
        displayPlus2_4Lbl = new javax.swing.JLabel();
        lottoResultsLbl = new javax.swing.JLabel();
        matchedNumsLbl = new javax.swing.JLabel();
        matchedMainDrawLbl = new javax.swing.JLabel();
        mainMatchedTextL1Lbl = new javax.swing.JLabel();
        mainMatchedTextL3Lbl = new javax.swing.JLabel();
        mainMatchedTextL2Lbl = new javax.swing.JLabel();
        matchedMainL1Lbl = new javax.swing.JLabel();
        matchedMainL2Lbl = new javax.swing.JLabel();
        matchedMainL3Lbl = new javax.swing.JLabel();
        matchedPlus1DrawLbl = new javax.swing.JLabel();
        plus1MatchedTextL1Lbl = new javax.swing.JLabel();
        plus1MatchedTextL3Lbl = new javax.swing.JLabel();
        plus1MatchedTextL2Lbl = new javax.swing.JLabel();
        matchedPlus1L1Lbl = new javax.swing.JLabel();
        matchedPlus1L2Lbl = new javax.swing.JLabel();
        matchedPlus1L3Lbl = new javax.swing.JLabel();
        matchedPlus2DrawLbl = new javax.swing.JLabel();
        plus2MatchedTextL1Lbl = new javax.swing.JLabel();
        plus2MatchedTextL3Lbl = new javax.swing.JLabel();
        plus2MatchedTextL2Lbl = new javax.swing.JLabel();
        matchedPlus2L1Lbl = new javax.swing.JLabel();
        matchedPlus2L2Lbl = new javax.swing.JLabel();
        matchedPlus2L3Lbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        playPhase1Btn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        lottoPlusAnsLbl = new javax.swing.JLabel();
        verifyButtonPressedLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        titleLbl.setText("Lotto Phase 2");

        headingLbl.setText("Would you like to play the Lotto Plus draws?");

        yesBtn.setText("Yes");
        yesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBtnActionPerformed(evt);
            }
        });

        noBtn.setText("No");
        noBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBtnActionPerformed(evt);
            }
        });

        playingPlusLbl.setText("Playing Lotto Plus:");

        selectLbl.setText("Please select your numbers from 1 - 40. (Please input a number in all fields)");

        line1Lbl.setText("Line 1:");

        playGameBtn.setText("Play Game");
        playGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameBtnActionPerformed(evt);
            }
        });

        line2Lbl.setText("Line 2:");

        line3Lbl.setText("Line 3:");

        resultsLbl.setText("Main draw:");

        resultsLbl1.setText("Plus 1 Draw:");

        resultsLbl2.setText("Plus 2 Draw:");

        lottoResultsLbl.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        lottoResultsLbl.setText("Lotto Results:");

        matchedNumsLbl.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        matchedNumsLbl.setText("Numbers Matched:");

        matchedMainDrawLbl.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        matchedMainDrawLbl.setText("Main Draw:");

        mainMatchedTextL1Lbl.setText("Numbers matched on line 1:");

        mainMatchedTextL3Lbl.setText("Numbers matched on line 3:");

        mainMatchedTextL2Lbl.setText("Numbers matched on line 2:");

        matchedPlus1DrawLbl.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        matchedPlus1DrawLbl.setText("Lotto Plus 1:");

        plus1MatchedTextL1Lbl.setText("Numbers matched on line 1:");

        plus1MatchedTextL3Lbl.setText("Numbers matched on line 3:");

        plus1MatchedTextL2Lbl.setText("Numbers matched on line 2:");

        matchedPlus2DrawLbl.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        matchedPlus2DrawLbl.setText("Lotto Plus 2:");

        plus2MatchedTextL1Lbl.setText("Numbers matched on line 1:");

        plus2MatchedTextL3Lbl.setText("Numbers matched on line 3:");

        plus2MatchedTextL2Lbl.setText("Numbers matched on line 2:");

        backBtn.setText("<- Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        playPhase1Btn.setText("Play Lotto Phase 1");
        playPhase1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playPhase1BtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        verifyButtonPressedLbl.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(titleLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(line1Lbl)
                            .addComponent(line3Lbl)
                            .addComponent(line2Lbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(line00Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line01Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line02Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line03Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line04Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(line10Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line11Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line12Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line13Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line14Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(line20Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line21Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line22Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line23Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line24Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(playGameBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resultsLbl)
                        .addGap(11, 11, 11)
                        .addComponent(displayResults0Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displayResults1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayResults2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayResults3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayResults4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resultsLbl1)
                        .addGap(11, 11, 11)
                        .addComponent(displayPlus1_0Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displayPlus1_1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayPlus1_2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayPlus1_3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayPlus1_4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lottoResultsLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resultsLbl2)
                        .addGap(11, 11, 11)
                        .addComponent(displayPlus2_0Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displayPlus2_1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayPlus2_2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayPlus2_3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayPlus2_4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addComponent(playingPlusLbl)
                            .addGap(18, 18, 18)
                            .addComponent(lottoPlusAnsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(selectLbl)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(verifyButtonPressedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(yesBtn)
                            .addGap(117, 117, 117)
                            .addComponent(noBtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mainMatchedTextL2Lbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(matchedMainL2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mainMatchedTextL3Lbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(matchedMainL3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mainMatchedTextL1Lbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(matchedMainL1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(plus1MatchedTextL3Lbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(matchedPlus1L3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(plus1MatchedTextL2Lbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(matchedPlus1L2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(plus2MatchedTextL1Lbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(matchedPlus2L1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(plus2MatchedTextL3Lbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(matchedPlus2L3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(plus2MatchedTextL2Lbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(matchedPlus2L2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(matchedNumsLbl)
                                            .addComponent(matchedMainDrawLbl)
                                            .addComponent(matchedPlus1DrawLbl)
                                            .addComponent(matchedPlus2DrawLbl))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(plus1MatchedTextL1Lbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(matchedPlus1L1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(79, 79, 79))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(playPhase1Btn)
                                .addGap(56, 56, 56)))
                        .addComponent(plus1Results2Lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitBtn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(headingLbl)
                        .addGap(98, 98, 98))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGap(52, 52, 52)
                .addComponent(headingLbl)
                .addGap(18, 18, 18)
                .addComponent(verifyButtonPressedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesBtn)
                    .addComponent(noBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playingPlusLbl)
                    .addComponent(lottoPlusAnsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(selectLbl)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(line1Lbl)
                    .addComponent(line00Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line01Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line02Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line03Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line04Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(line10Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line11Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line12Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line13Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line14Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line2Lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(line20Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line21Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line22Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line23Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line24Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line3Lbl)
                    .addComponent(playGameBtn))
                .addGap(35, 35, 35)
                .addComponent(lottoResultsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(displayResults0Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayResults1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayResults2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayResults3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayResults4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resultsLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(displayPlus1_0Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayPlus1_1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayPlus1_2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayPlus1_3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayPlus1_4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resultsLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(displayPlus2_0Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayPlus2_1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayPlus2_2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayPlus2_3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayPlus2_4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resultsLbl2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(plus1Results2Lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(matchedNumsLbl)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(matchedMainDrawLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(mainMatchedTextL1Lbl)
                                            .addComponent(matchedMainL1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mainMatchedTextL2Lbl))
                                    .addComponent(matchedMainL2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainMatchedTextL3Lbl))
                            .addComponent(matchedMainL3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(matchedPlus1DrawLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(plus1MatchedTextL1Lbl)
                                            .addComponent(matchedPlus1L1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plus1MatchedTextL2Lbl))
                                    .addComponent(matchedPlus1L2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plus1MatchedTextL3Lbl))
                            .addComponent(matchedPlus1L3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(matchedPlus2DrawLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(plus2MatchedTextL1Lbl)
                                            .addComponent(matchedPlus2L1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plus2MatchedTextL2Lbl))
                                    .addComponent(matchedPlus2L2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plus2MatchedTextL3Lbl))
                            .addComponent(matchedPlus2L3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backBtn)
                            .addComponent(playPhase1Btn)
                            .addComponent(exitBtn))
                        .addGap(35, 35, 35))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        
        //create a new instance of phase 2 gui:
        
        LottoPhase2GUI p2GUI = new LottoPhase2GUI();
        p2GUI.setVisible(false);
        dispose();
        
        LottoMainGUI mainGUI = new LottoMainGUI();
        mainGUI.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void playPhase1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playPhase1BtnActionPerformed
        LottoPhase2GUI p2GUI = new LottoPhase2GUI();
        p2GUI.setVisible(false);
        dispose();
        
        LottoPhase1GUI p1GUI = new LottoPhase1GUI();
        p1GUI.setVisible(true);
    }//GEN-LAST:event_playPhase1BtnActionPerformed

    private void yesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBtnActionPerformed
        lottoPlusAnsLbl.setText("YES");
    }//GEN-LAST:event_yesBtnActionPerformed

    private void noBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBtnActionPerformed
        lottoPlusAnsLbl.setText("NO");
    }//GEN-LAST:event_noBtnActionPerformed

    private void playGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameBtnActionPerformed
        
        //Assign values to array list from text fields on LottoPhase2MainDraw:
        
        num[0][0] = Integer.parseInt(line00Tf.getText());
        num[0][1] = Integer.parseInt(line01Tf.getText());
        num[0][2] = Integer.parseInt(line02Tf.getText());
        num[0][3] = Integer.parseInt(line03Tf.getText());
        num[0][4] = Integer.parseInt(line04Tf.getText());
        num[1][0] = Integer.parseInt(line10Tf.getText());
        num[1][1] = Integer.parseInt(line11Tf.getText());
        num[1][2] = Integer.parseInt(line12Tf.getText());
        num[1][3] = Integer.parseInt(line13Tf.getText());
        num[1][4] = Integer.parseInt(line14Tf.getText());
        num[2][0] = Integer.parseInt(line20Tf.getText());
        num[2][1] = Integer.parseInt(line21Tf.getText());
        num[2][2] = Integer.parseInt(line22Tf.getText());
        num[2][3] = Integer.parseInt(line23Tf.getText());
        num[2][4] = Integer.parseInt(line24Tf.getText());
        
        playingLottoPlus = lottoPlusAnsLbl.getText();
        
        // create a new instance of LottoPhase2MainDraw:
        
        LottoPhase2MainDraw p2Main = new LottoPhase2MainDraw();
        
        if(playingLottoPlus.equals("NO")){
            verifyButtonPressedLbl.setText("");
            
            p2Main.setNum(num);
            p2Main.createSecret();
            secretMain = p2Main.getSecret();
            p2Main.computeCheckInput();
            correctL1Main = p2Main.getCorrectL1();
            correctL2Main = p2Main.getCorrectL2();
            correctL3Main = p2Main.getCorrectL3(); // runs Main draw
            
            displayResults0Lbl.setText(Integer.toString(secretMain[0]));
            displayResults1Lbl.setText(Integer.toString(secretMain[1]));
            displayResults2Lbl.setText(Integer.toString(secretMain[2]));
            displayResults3Lbl.setText(Integer.toString(secretMain[3]));
            displayResults4Lbl.setText(Integer.toString(secretMain[4])); // displays Main results in each number's own label

            matchedMainL1Lbl.setText(Integer.toString(correctL1Main));
            matchedMainL2Lbl.setText(Integer.toString(correctL2Main));
            matchedMainL3Lbl.setText(Integer.toString(correctL3Main)); // displays amount of matched numbers from Main Draw
            
            displayPlus1_0Lbl.setText("");
            displayPlus1_1Lbl.setText("");
            displayPlus1_2Lbl.setText("");
            displayPlus1_3Lbl.setText("");
            displayPlus1_4Lbl.setText(""); // resets results to empty if Yes is selected first.
            
            displayPlus2_0Lbl.setText("");
            displayPlus2_1Lbl.setText("");
            displayPlus2_2Lbl.setText("");
            displayPlus2_3Lbl.setText("");
            displayPlus2_4Lbl.setText(""); // resets results to empty if Yes is selected first.

            matchedPlus1L1Lbl.setText("Not played");
            matchedPlus1L2Lbl.setText("Not played");
            matchedPlus1L3Lbl.setText("Not played"); // informs user they didn't play Plus 1 draw
            
            matchedPlus2L1Lbl.setText("Not played");
            matchedPlus2L2Lbl.setText("Not played");
            matchedPlus2L3Lbl.setText("Not played"); // informs user they didn't play Plus 2 draw
            
        }
        
        else if(playingLottoPlus.equals("YES")){
             
            verifyButtonPressedLbl.setText("");
            
            p2Main.setNum(num);
            p2Main.createSecret();
            secretMain = p2Main.getSecret();
            p2Main.computeCheckInput();
            correctL1Main = p2Main.getCorrectL1();
            correctL2Main = p2Main.getCorrectL2();
            correctL3Main = p2Main.getCorrectL3(); // runs Main draw
            
            displayResults0Lbl.setText(Integer.toString(secretMain[0]));
            displayResults1Lbl.setText(Integer.toString(secretMain[1]));
            displayResults2Lbl.setText(Integer.toString(secretMain[2]));
            displayResults3Lbl.setText(Integer.toString(secretMain[3]));
            displayResults4Lbl.setText(Integer.toString(secretMain[4])); // displays Main results in each number's own label
            
            matchedMainL1Lbl.setText(Integer.toString(correctL1Main));
            matchedMainL2Lbl.setText(Integer.toString(correctL2Main));
            matchedMainL3Lbl.setText(Integer.toString(correctL3Main));
            
            LottoPhase2Plus1 p2Plus1 = new LottoPhase2Plus1();
            p2Plus1.setNum(num);
            p2Plus1.createSecret();
            secretPlus1 = p2Plus1.getSecret();
            p2Plus1.computeCheckInputP1();
            correctL1Plus1 = p2Plus1.getCorrectL1();
            correctL2Plus1 = p2Plus1.getCorrectL2();
            correctL3Plus1 = p2Plus1.getCorrectL3(); //runs Plus 1 Draw
                        
            displayPlus1_0Lbl.setText(Integer.toString(secretPlus1[0]));
            displayPlus1_1Lbl.setText(Integer.toString(secretPlus1[1]));
            displayPlus1_2Lbl.setText(Integer.toString(secretPlus1[2]));
            displayPlus1_3Lbl.setText(Integer.toString(secretPlus1[3]));
            displayPlus1_4Lbl.setText(Integer.toString(secretPlus1[4])); // displays Plus 1 results in each number's own label
            
            matchedPlus1L1Lbl.setText(Integer.toString(correctL1Plus1));
            matchedPlus1L2Lbl.setText(Integer.toString(correctL2Plus1));
            matchedPlus1L3Lbl.setText(Integer.toString(correctL3Plus1)); // displays amount of matched numbers from Plus 1 Draw
            
            
            LottoPhase2Plus2 p2Plus2 = new LottoPhase2Plus2();
            p2Plus2.setNum(num);
            p2Plus2.createSecret();
            secretPlus2 = p2Plus2.getSecret();
            p2Plus2.computeCheckInputP2();
            correctL1Plus2 = p2Plus2.getCorrectL1();
            correctL2Plus2 = p2Plus2.getCorrectL2();
            correctL3Plus2 = p2Plus2.getCorrectL3(); //runs Plus 2 Draw

            displayPlus2_0Lbl.setText(Integer.toString(secretPlus2[0]));
            displayPlus2_1Lbl.setText(Integer.toString(secretPlus2[1]));
            displayPlus2_2Lbl.setText(Integer.toString(secretPlus2[2]));
            displayPlus2_3Lbl.setText(Integer.toString(secretPlus2[3]));
            displayPlus2_4Lbl.setText(Integer.toString(secretPlus2[4])); // displays Plus 2 results in each number's own label
            
            matchedPlus2L1Lbl.setText(Integer.toString(correctL1Plus2));
            matchedPlus2L2Lbl.setText(Integer.toString(correctL2Plus2));
            matchedPlus2L3Lbl.setText(Integer.toString(correctL3Plus2)); // displays amount of matched numbers from Plus 2 Dra
        }
        
        else{
            verifyButtonPressedLbl.setText("Please click Yes or No");
        }
    }//GEN-LAST:event_playGameBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LottoPhase2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LottoPhase2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LottoPhase2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LottoPhase2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LottoPhase2GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel displayPlus1_0Lbl;
    private javax.swing.JLabel displayPlus1_1Lbl;
    private javax.swing.JLabel displayPlus1_2Lbl;
    private javax.swing.JLabel displayPlus1_3Lbl;
    private javax.swing.JLabel displayPlus1_4Lbl;
    private javax.swing.JLabel displayPlus2_0Lbl;
    private javax.swing.JLabel displayPlus2_1Lbl;
    private javax.swing.JLabel displayPlus2_2Lbl;
    private javax.swing.JLabel displayPlus2_3Lbl;
    private javax.swing.JLabel displayPlus2_4Lbl;
    private javax.swing.JLabel displayResults0Lbl;
    private javax.swing.JLabel displayResults1Lbl;
    private javax.swing.JLabel displayResults2Lbl;
    private javax.swing.JLabel displayResults3Lbl;
    private javax.swing.JLabel displayResults4Lbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JTextField line00Tf;
    private javax.swing.JTextField line01Tf;
    private javax.swing.JTextField line02Tf;
    private javax.swing.JTextField line03Tf;
    private javax.swing.JTextField line04Tf;
    private javax.swing.JTextField line10Tf;
    private javax.swing.JTextField line11Tf;
    private javax.swing.JTextField line12Tf;
    private javax.swing.JTextField line13Tf;
    private javax.swing.JTextField line14Tf;
    private javax.swing.JLabel line1Lbl;
    private javax.swing.JTextField line20Tf;
    private javax.swing.JTextField line21Tf;
    private javax.swing.JTextField line22Tf;
    private javax.swing.JTextField line23Tf;
    private javax.swing.JTextField line24Tf;
    private javax.swing.JLabel line2Lbl;
    private javax.swing.JLabel line3Lbl;
    private javax.swing.JLabel lottoPlusAnsLbl;
    private javax.swing.JLabel lottoResultsLbl;
    private javax.swing.JLabel mainMatchedTextL1Lbl;
    private javax.swing.JLabel mainMatchedTextL2Lbl;
    private javax.swing.JLabel mainMatchedTextL3Lbl;
    private javax.swing.JLabel matchedMainDrawLbl;
    private javax.swing.JLabel matchedMainL1Lbl;
    private javax.swing.JLabel matchedMainL2Lbl;
    private javax.swing.JLabel matchedMainL3Lbl;
    private javax.swing.JLabel matchedNumsLbl;
    private javax.swing.JLabel matchedPlus1DrawLbl;
    private javax.swing.JLabel matchedPlus1L1Lbl;
    private javax.swing.JLabel matchedPlus1L2Lbl;
    private javax.swing.JLabel matchedPlus1L3Lbl;
    private javax.swing.JLabel matchedPlus2DrawLbl;
    private javax.swing.JLabel matchedPlus2L1Lbl;
    private javax.swing.JLabel matchedPlus2L2Lbl;
    private javax.swing.JLabel matchedPlus2L3Lbl;
    private javax.swing.JButton noBtn;
    private javax.swing.JButton playGameBtn;
    private javax.swing.JButton playPhase1Btn;
    private javax.swing.JLabel playingPlusLbl;
    private javax.swing.JLabel plus1MatchedTextL1Lbl;
    private javax.swing.JLabel plus1MatchedTextL2Lbl;
    private javax.swing.JLabel plus1MatchedTextL3Lbl;
    private javax.swing.JLabel plus1Results2Lbl1;
    private javax.swing.JLabel plus2MatchedTextL1Lbl;
    private javax.swing.JLabel plus2MatchedTextL2Lbl;
    private javax.swing.JLabel plus2MatchedTextL3Lbl;
    private javax.swing.JLabel resultsLbl;
    private javax.swing.JLabel resultsLbl1;
    private javax.swing.JLabel resultsLbl2;
    private javax.swing.JLabel selectLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel verifyButtonPressedLbl;
    private javax.swing.JButton yesBtn;
    // End of variables declaration//GEN-END:variables
}
